meta_product_name: "Characterize"
meta_title: "Characterize - Build your backstory"
meta_description: "A character backstory builder for the struggling player or dungeon master."
meta_image: "cover.png"
